# Generated by Django 3.0.7 on 2020-07-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='What is your Name ?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cricketer_name', models.CharField(choices=[('Sachin Tendulkar', 'sachin tendulkar'), ('Virat Kohli', 'virat kohli'), ('Adam Gilchirst', 'adam gilchirst'), ('Jacques Kallis', 'jacques kallis')], default='virat kohli', max_length=45, verbose_name='who is the Best cricketer in the world ?')),
                ('white', models.BooleanField(default=False, verbose_name='WHITE color present in indian flag ?')),
                ('yellow', models.BooleanField(default=False, verbose_name='YELLOW color present in indian flag ?')),
                ('orange', models.BooleanField(default=False, verbose_name='ORANGE color present in indian flag ?')),
                ('green', models.BooleanField(default=False, verbose_name='GREEN color present in indian flag ?')),
            ],
        ),
    ]
